apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorturl
spec:
  selector:
    matchLabels:
      app: shorturl
  template:
    metadata:
      labels:
        app: shorturl
    spec:
      containers:
      - name: shortenurlapp
        image: abdo3001/short_url:770d83b1e0f04255096938cd694c97947384e5ff
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
